server {
	listen 443 ssl;
	server_name listingtracker.xyz www.listingtracker.xyz;
    disable_symlinks off;
    client_max_body_size 100M;

	ssi on;
	ssl_certificate /var/www/app/certs/pem;
    ssl_certificate_key /var/www/app/certs/key;

    index index.php;
    root /var/www/app/public;

	location / {
		try_files $uri $uri/ /index.php?$args;
    }

	location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
